Fix for the crash that makes app unusable for all devices running Android lower than 8.0: Bug was introduced during all-dependencies-version-upgrade commit. It turns out that all apache commons libraries started to require support for Android 8 after a certain version. Devices running Android lower than 8.0 are incapable of desugaring Java 8. This fix downgrades those dependencies to the last version that doesn't require Java 8. It's a temporary measure, because we cannot allow ourselves to get stuck on ever-more outdated dependencies, hence the future proper fix would be to replace the job that was done by those libraries with different ones. In Crashlytics this fix should address most of the various crashes that start with Exception: "java.lang.NoSuchMethodError"